[project]
name = "omnitool"
version = "0.2.0"
description = ""
authors = [
    {name = "jan-mski",email = "36985396+jan-mski@users.noreply.github.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-settings (>=2.8.1,<3.0.0)",
    "omnitool-plugin-base @ git+ssh://git@github.com/jan-mski/omnitool-plugin-base.git@main",
    "omnitool-git-plugin @ git+ssh://git@github.com/jan-mski/omnitool-git-plugin.git@omn-17"
]

[tool.poetry]
packages = [
    { include = "omnitool" },
]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"
pytest-cov = "^6.0.0"
pytest-mock = "^3.14.0"
factory-boy = "^3.3.3"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
