version: 2.1

# See: https://circleci.com/docs/orb-intro/
orbs:
  # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
  python: circleci/python@3.0.0

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.12.9
    steps:
      - run: # https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
          name: Add Github's SSH key fingerprint
          command: mkdir -p ~/.ssh && echo -e "github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl" >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "SHA256:J0ZPyjQqwh3y5yLkUEfkbVYUBzaQ5yXqSbGOm7VNzFQ"
      - checkout
      - python/install-packages:
          pkg-manager: uv # https://circleci.com/developer/orbs/orb/circleci/python#usage-work-with-uv
      - run:
          name: Run tests
          command: uv run pytest

# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  omnitool:
    jobs:
      - build-and-test
