version: 2.1

orbs:
  python: circleci/python@4.0.0

jobs:
  build:
    executor:
      name: python/default
      tag: '3.13'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - run:
          command: |
            uv run pytest --version
          name: Test it
workflows:
  main:
    jobs:
      - build
